trigger:
  - master
pr:
  - master

pool:
  vmImage: 'macos-latest'

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: ':server:build :server:check'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Płatność zgodnie z rzeczywistym użyciem(9ba7cd00-af61-43d5-ba8b-8a82e68a7d5a)'
      appType: 'webAppLinux'
      WebAppName: 'bng-test'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/server-*all.jar'
      RuntimeStack: 'JAVA|11-java11'
      StartupCommand: 'java -jar server-1.0-SNAPSHOT-all.jar --server.port=443'
